### ISSUE TITLE
Following Ularcirc tutorial gives error

### ISSUE THREAD

**Issue by ddiez** [VCCRI/Ularcirc#1]
I am trying to follow the tutorial in the [vignette](https://www.bioconductor.org/packages/release/bioc/html/Ularcirc.html) and getting an error when trying to perform step 3 (building the annotations). Here is the output from the R console:

These messages appear upon running `Ularcirc()`:

```
> Ularcirc()

Listening on http://127.0.0.1:6085
Warning in min(Gene_Transcripts$Transcript$start) :
  no non-missing arguments to min; returning Inf
Warning in max(Gene_Transcripts$Transcript$stop) :
  no non-missing arguments to max; returning -Inf
```

This appears after navigating to the Gene-View tab (NOTE: the example project file TwoSzabo has been successfully loaded and I can see two files SRR1721284 and SRR1721290 in the selected samples):

```
Loading species transcriptome coordinates Fri Nov 16 16:54:30 2018
  Displaying list of  61050  genes built Fri Nov 16 16:54:30 2018Warning in IdentifyDataSets() :
  No data loaded or selected so nothing to display
Please navigate back to PROJECT tab and load a data set
```
I select `Annotate with parental gene:` in the Gene-View tab and click `Annotate`. I get the following message and the app terminates:

```
Warning: Error in if: argument is of length zero
  73: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Ularcirc/shiny-app/circRNA/server.R#1488]
   2: shiny::runApp
   1: Ularcirc
```

**Comment by davhum** [comment]
Hi Ddiez,

This is an unexpected error. Can you confirm that on the Gene_view tab there is a pull down menu under "Data sets to analyse" (refer to image below). The default should be "Selected sample analysis".  The error that you are reporting suggests this field is not populating with predefined entries. 

![image](https://user-images.githubusercontent.com/4456671/48686096-584def80-ec0e-11e8-9a76-05073f3d6a80.png)

**Comment by ddiez** [comment]
Yes, this is how it looks like:

![screen shot 2018-11-19 at 13 40 21](https://user-images.githubusercontent.com/3292149/48686733-dc00df80-ec00-11e8-92f9-eb5c2aedeb88.png)

After that I check `Annotate with parental gene` and click `Annotate`, which triggers the above error.

**Comment by davhum** [comment]
The example data file was corrupt and caused issues upon loading. To fix only need to download the TwoSzabo.Rdata file (or just reinstall). Let me know if you have any further issues/questions. 

Also keep an eye out for an updated Ularcirc release later this week.

**Comment by ddiez** [comment]
Downloading and replacing the file works perfect. Thanks! Reinstalling I guess you mean from github and not Bioconductor, since it doesn't seem to be updated there yet. But I'll keep an eye on the forthcoming update!
