### ISSUE TITLE
Problem with BS junction sequences

### ISSUE THREAD

**Issue by YunaBlum** [VCCRI/Ularcirc#16]
Hi David,
First, thank you for your great tool. I'm wondering why the BS junction sequence do not match the acceptor / donor sequences from the circRNA sequence. This is the case as well with your example project TwoSzabo. Do you have any explanation?
In your function Grab_BS_Junc_Sequence, I'm not sure why you have the following lines for, which might cause the pb:
```{r}
    if (TranscriptStrand =="+")
    TranscriptStrand <- "-"
    else
    TranscriptStrand <- "+"
```
Thank you in avance,
Yuna

**Comment by davhum** [comment]
Hi Yuna,

Thanks for raising this as I was not aware of an there being an error generating the BS junction sequence. Note that the predicted circRNA sequence does look correct, please let me know if this is what you were referring to. 

Will fix BS junction sequence ASAP. Sorry for delay, should be done in next 24hrs.
D

**Comment by YunaBlum** [comment]
Thank you very much, please let me know when it is fixed!
Best,
yuna

**Comment by davhum** [comment]
I have updated code and have done some testing across vignette example. Appears to recover correct sequence now. Let me know if you find anything else.
Regards,
Dave
