### ISSUE TITLE
Ularcirc crashing with STAR data and gene annotation

### ISSUE THREAD

**Issue by fenguita** [VCCRI/Ularcirc#17]
Hi
I am dealing with BSJ and FSJ data generated from STAR. When I tried to display table annotated by genes under the "Gene_View" section, the program crashed. It happens with my data and also with the test data that is coming with the software.

What I am doing wrong?

Thanks for your help

**Comment by davhum** [comment]
Are there any error messages displayed? I wonder if all dependencies were correctly loaded.

**Comment by fenguita** [comment]
Hi again
Thanks for your answer...maybe you are right... I was running R in windoze and I switch for Linux. So, in Linux everything appears to work.
Congrats for such amazing tool

**Comment by davhum** [comment]
Good to hear. It should work also on windows. I will close this for now, but feel free to re-open and post error message if you still have issues
