### ISSUE TITLE
Couldn't visit Youtube

### ISSUE THREAD

**Issue by gnilihzeux** [VCCRI/Ularcirc#2]
Dear author,    
    It's very interesting of your Ularcirc, and I had read through your paper and installed your software.     
    But I suffered a issue that **ORGANISM** of part setup seems not work and report `Error: invalid 'pattern' argument`
   By the way, we couldn't visit demonstrates of Youtube from china, however there are more players of circRNA study in China.

**Comment by davhum** [comment]
Dear Jinwen,

Thanks for your message. Can you confirm which species you are working with and if the annotations databases are installed. For example if you are working with Human or mouse data can you tell me the output of the following commands:

p <- installed.packages()
p[grep(pattern = "Hs",x = p[,1])]
p[grep(pattern = "Mm",x = p[,1])]


For the  video can you recommend a publically accessible website that you can access such content from.

Regards,
Dave

**Comment by gnilihzeux** [comment]
Sorry for my late reply.

With your tips, the Ularcirc did work after some packages such as 'BSgenome' installed.  I will try more to learn this softwares.

As for video website, there doesn't seems to be an international one. Our popular websites are all in Chinese, such as [Bilibili](https://www.bilibili.com).
