### ISSUE TITLE
Cannot upload new data

### ISSUE THREAD

**Issue by circR** [VCCRI/Ularcirc#3]
Hi David
Thank you for this tool. I had a problem with the "upload new data" function.
I tried the "SRR444655.Chimeric.out.junction" file and it seems working. However, when I upload my own Chimeric.out.junction file, the webpage just closes. I also tried with the output file of CIRCexplorer2 and the webpage also closes. Can you help with this? Thank you a lot.
 
Here's the information from RStudio;
Loading data SRR444655.Chimeric.out.junction 
Loading data 10872179 
Loading data  
Loading data C:\Users\DC\AppData\Local\Temp\RtmpWE73jR/20e277aa12d290a2a451f945/0.junction
Loading data circularRNA_know_sort_1.txt 
Loading data 229190 
Loading data text/plain 
Loading data C:\Users\DC\AppData\Local\Temp\RtmpWE73jR/ba54d2d98a1aa49d2581e931/0.txtWarning: Error in <-: replacement has length zero
  77: eval [C:\Program Files\R\R-3.6.1\library\Ularcirc\shiny-app\circRNA/server.R#928]
  76: eval
  75: withProgress
  74: LoadJunctionData [C:\Program Files\R\R-3.6.1\library\Ularcirc\shiny-app\circRNA/server.R#733]
  73: observeEventHandler [C:\Program Files\R\R-3.6.1\library\Ularcirc\shiny-app\circRNA/server.R#1847]
   2: shiny::runApp
   1: Ularcirc

**Comment by davhum** [comment]
Thanks for getting in touch. Can you confirm the naming of your Chimeric.out.junction file, it appears to be named 0.junction. If so please rename to sample.Chimeric.out.junction.

Similarly your circExplorer output should be named from circRNA_know_sort_1.txt to  sample.ce

As you can see Ularcirc requires specific file extensions to recognise the data file. I need to put a fix in to catch if no file is recognised – this is most likely why it just closed down on you.


Let me know if the file renaming solves the problem.
Regards,
Dave

**Comment by circR** [comment]
Hi 
Thanks for replying.
Renaming the file solved the uploading problem. I have another issue. 
I'm using the C. elegans genome. I loaded the genome and refGene data.
![image](https://user-images.githubusercontent.com/34292024/64756756-f37fcf00-d56a-11e9-8f85-6701534b99bf.png)
Then I upload the Circexplorer2 output file using "sample.ce" as its name without any problem. 
However, when I navigated to Gene_view panel, a warning message appeared. 

Loading species transcriptome coordinates Thu Sep 12 14:37:29 2019
  Displaying list of  46857  genes built Thu Sep 12 14:37:29 2019
Loading data s1.ce 
Loading data 229190 
Loading data  
Loading data C:\Users\DC\AppData\Local\Temp\RtmpSC9dj8/f3015252fea6a6872340408c/0.ceWarning in IdentifyDataSets() :
  No data loaded or selected so nothing to display
Please navigate back to PROJECT tab and load a data set

I can build the BSJ table as below:
![image](https://user-images.githubusercontent.com/34292024/64757115-06df6a00-d56c-11e9-9b7b-3fddf978c4a7.png)
But when I chose one gene to show the transcript, another error appeared.
Requesting Gene Object for zip-2 Thu Sep 12 14:46:26 2019Warning: Error in if: argument is of length zero
  185: <reactive> [C:\Program Files\R\R-3.6.1\library\Ularcirc\shiny-app\circRNA/server.R#2604]
  183: .func
  180: contextFunc
  179: env$runWith
  172: ctx$run
  171: self$.updateValue
  169: circRNA_Subset
  168: renderPlot [C:\Program Files\R\R-3.6.1\library\Ularcirc\shiny-app\circRNA/server.R#3731]
  166: func
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$plotFSJ_BSJ_GeneModel
    2: shiny::runApp
    1: Ularcirc
Warning: Error in if: argument is of length zero
  100: <Anonymous>
![image](https://user-images.githubusercontent.com/34292024/64757181-473ee800-d56c-11e9-91f4-6a9e006db404.png)

Can you help with this?
Thank you.

**Comment by davhum** [comment]
I suspect this might be a coding error relating to no FSJ file being present. As you aligned data with STAR would you mind uploading the SJ.tab.out file. To do this rename the SJ.tab.out to have the same file prefix (which in your case would be s1.SJ.out.tab). 

Note you will have to upload both s1.SJ.out.tab and s1.ce at the same time. Therefore make sure both files are in the same directory/folder so that you can select them both.

Let me know if this fixes the situation as this will confirm that I need to put another checkpoint in code.

**Comment by circR** [comment]
Hi David
Yes, it works after uploading the SJ.tab.out and Circexplorer2 file.
Thank you for your great help.

**Comment by davhum** [comment]
Have updated code which should catch filename errors.
