### ISSUE TITLE
Essential Dependencies Not Installed Automatically

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#4]
I installed the software from Bioconductor, but it takes a multiple tries to get the application to run. Firstly, I didn't have shinydashboard installed. Then, I reloaded it and found it also requires shinyjs. Eventually, after also installing moments and Organism.dplyr, it runs. Perhaps these should be in the Imports field of the DESCRIPTION file, so they are automatically installed when Ularcirc is installed.

Also, the README file contains an instruction which Bioconductor no longer supports and produces an error in contemporary versions of R.

```r
source("http://bioconductor.org/biocLite.R")
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager
```

**Comment by davhum** [comment]
Closing this issue as last update added dependencies to DESCRIPTION field as suggested. Also Amended README file as suggested.
Appreciate you letting me know Dario.
Thanks
