### ISSUE TITLE
Annotate With Parental Gene Missing

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#5]
I read the instruction "on the left hand panel select Annotate with parental gene" in the vignette but my view doesn't seem to have that option. If I click on Build Table, I get an error No Data Loaded, although I seem to have successfully loaded TwoSzabo. I can see two samples with checked check boxes in the Selected Sample section of the Project tab.

![image](https://user-images.githubusercontent.com/631218/67356151-f081f080-f5a4-11e9-8965-125b3d8f6243.png)

**Comment by davhum** [comment]
Hi Dario, 
Indeed it appears that the TwoSzabo dataset has been loaded. It appears the TwoSzabo data set is out of date as Ularcirc cannot detect BSJ data. Can I double check if you downloaded this from bioconductor (developer or standard release). I am hoping this is only related to the standard release which should be updated with the next release that is happening very soon.


You can get around this problem in the short term by downloaded the TwoSzabo data set from github (https://github.com/VCCRI/Ularcirc/blob/master/inst/extdata/TwoSzabo.RData).
 This file will need to be placed in the extdata folder within your Ularcirc R libaries folder. 
Actually  would be easier/faster if you install Ularcirc from github (which I believe is identical to bioconductor developer).   

I will look into this in more detail tomorrow. I have also seen your other post and will update accordingly. Thanks for taking the time to let me know of these issues.
Regards,
D

**Comment by DarioS** [comment]
I updated all Bioconductor package so Ularcirc 1.4.0 is used and it now works.
