### ISSUE TITLE
Name Prefix Must End with Period But Not Documented

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#6]
For STAR's `--outFileNamePrefix`, it adds the suffixes directly to the end the prefix without any delimiter. For example, if the prefix is Patient1, the file name of the splice junctions file will be Patient1SJ.out.tab. However, Ularcirc demands that there is a period separating the prefix from the suffix, which is not what STAR does by default.

> File must end with either .SJ.out.tab **or** .ReadsPerGene.out.tab **or** .Chimeric.out.junction
**Please review the following files that failed to upload:**
OC1hg38Chimeric.out.junction
OC1hg38SJ.out.tab

Can the period be optional since STAR doesn't use one to separate the prefix from the suffix? In the meantime, I'll work around it by using soft links.

**Comment by davhum** [comment]
Good points. have updated so that both naming conventions can be accepted.
