### ISSUE TITLE
Chimeric File Crashes Ularcirc

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#7]
To enable STAR's chimeric output files to work with [STAR-Fusion](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1842-9), the option `--chimOutJunctionFormat 1` is used. Loading such a file into Ularcirc causes the application to crash with a traceback

```r
Detected 21 column names but the data has 20 columns. Filling rows automatically. Set fill=TRUE explicitly to avoid this warning.
Warning: Error in : non-numeric argument to binary operator
  78: FilterChimeric [/dskh/nobackup/biostat/Bioconductor/Ularcirc/shiny-app/circRNA/Server.R#979]
  74: LoadJunctionData [/dskh/nobackup/biostat/Bioconductor/Ularcirc/shiny-app/circRNA/Server.R#733]
  73: observeEventHandler [/dskh/nobackup/biostat/Bioconductor/Ularcirc/shiny-app/circRNA/Server.R#1847]
```

I don't know if that's related to the crash, but it's the only difference to the default output I can think of.

**Comment by davhum** [comment]
Hi Dario,

Thanks for bringing this to my attention. The new chimOutJunctionFormat introduces more columns and this caused the error. Have fixed error in latest update. Still need to re-work documentation so will leave this thread active until then.

**Comment by DarioS** [comment]
Ah, yes, the latest version stalls when it hits a `browser()` so still some code to modify before release.

**Comment by davhum** [comment]
Documentation has been updated along with a new section in vignette.
