### ISSUE TITLE
loadSTAR_chimeric Missing

### ISSUE THREAD

**Issue by DarioS** [VCCRI/Ularcirc#9]
Loading new files into the application terminates it with an error

```r
'loadSTAR_chimeric' is not an exported object from 'namespace:Ularcirc'
```

Searching the package's R code only finds a function call, not a definition, for `loadSTAR_chimeric`.

**Comment by davhum** [comment]
Have updated namespace -which should address the issue. 
Note I am having some trouble with my local machine performing R devtools checks. Therefore may be some other simple errors. I am currently on leave and will be able to fully address this next week.
Regards,
D
